-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- hl.config({
-- 	debug = {
-- 		disable_logs = false,
-- 		gl_debugging = true,
-- 	},
-- })

--###################
--## MY VARIABLES ###
--###################

local desktopScale = 1
-- local wallpapers = "~/.config/wallpapers/gifs/"

--###############
--## MONITORS ###
--###############
-- See https://wiki.hyprland.org/Configuring/Monitors/

hl.monitor({
	output = "eDP-1",
	mode = "1920x1080@120.03",
	-- mode = "1920x1080@48.01",
	position = "0x0",
	scale = desktopScale,
})

hl.config({
	xwayland = {
		force_zero_scaling = true,
	},
})

--##################
--## MY PROGRAMS ###
--##################
-- See https://wiki.hyprland.org/Configuring/Keywords/

-- Set programs that you use
local terminal = "ghostty"
local fileManager = "dolphin"
local runner = "walker"
local browser = "firefox"

--############################
--## ENVIRONMENT VARIABLES ###
--############################
-- See https://wiki.hyprland.org/Configuring/Environment-variables/

hl.env("XDG_CONFIG_HOME", "/home/shivraj/.config/")
hl.env("XDG_MENU_PREFIX", "arch-")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")

-- Nix profile environment (Desktop entries & binaries)
hl.env(
	"XDG_DATA_DIRS",
	"/home/shivraj/.nix-profile/share:/nix/var/nix/profiles/default/share:"
		.. (os.getenv("XDG_DATA_DIRS") or "/usr/local/share:/usr/share")
)
hl.env(
	"PATH",
	"/home/shivraj/.nix-profile/bin:/nix/var/nix/profiles/default/bin:"
		.. (os.getenv("PATH") or "/usr/local/bin:/usr/bin:/bin")
)

-- Colors & Appearance
hl.env("COLOR_BACKEND", "colorthief")

-- Cursor Styles
hl.env("XCURSOR_SIZE", 21)
hl.env("HYPRCURSOR_SIZE", 21)

-- Firefox Settings
hl.env("MOZ_DISABLE_RDD_SANDBOX", 1)

-- Graphics Card Selection
hl.env("AQ_DRM_DEVICES", "/dev/dri/card2:/dev/dri/card1")

-- NVIDIA Settings
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("XDG_SESSION_TYPE", "wayland")
-- hl.env("GBM_BACKEND", "nvidia-drm")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")

-- Steam Settings
hl.env("STEAM_FORCE_DESKTOPUI_SCALING", 1.25)

-- Toolkit-specific Scale
hl.env("GDK_SCALE", 1.25)
hl.env("QT_SCALE_FACTOR", 1.25)
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", 1.25)

--####################
--## LOOK AND FEEL ###
--####################
-- Refer to https://wiki.hyprland.org/Configuring/Variables/
-- https://wiki.hyprland.org/Configuring/Variables/#general

hl.config({
	general = {
		gaps_in = 2,
		gaps_out = 2,
		border_size = 1,
		-- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
		-- Set to true enable resizing windows by clicking and dragging on borders and gaps
		resize_on_border = false,
		-- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
		allow_tearing = false,
		layout = "dwindle",
		col = {
			active_border = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
			inactive_border = "rgba(595959aa)",
		},
	},
})

-- https://wiki.hyprland.org/Configuring/Variables/#decoration

hl.config({
	decoration = {
		rounding = 10,
		-- Change transparency of focused and unfocused windows
		active_opacity = 1.0,
		inactive_opacity = 0.85,
		border_part_of_window = false,
		shadow = {
			enabled = true,
			range = 4,
			render_power = 3,
			color = "rgba(1a1a1aee)",
		},
		-- https://wiki.hyprland.org/Configuring/Variables/#blur
		blur = {
			enabled = true,
			size = 8,
			passes = 2,
			vibrancy = 0.1696,
			ignore_opacity = true,
		},
	},
})

-- https://wiki.hyprland.org/Configuring/Variables/#animations

hl.config({
	animations = {
		enabled = true,
		-- Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
	},
})

-- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more

hl.config({
	dwindle = {
		preserve_split = true,
		-- You probably want this
	},
})

-- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more

hl.config({
	master = {
		new_status = "master",
	},
})

-- https://wiki.hyprland.org/Configuring/Variables/#misc

hl.config({
	misc = {
		force_default_wallpaper = 0,
		-- Set to 0 or 1 to disable the anime mascot wallpapers
		disable_hyprland_logo = true,
		-- If true disables the random hyprland logo / anime girl background. :(
	},
})

--############
--## INPUT ###
--############
-- https://wiki.hyprland.org/Configuring/Variables/#input

hl.config({
	input = {
		kb_layout = "us",
		kb_variant = "",
		kb_model = "",
		kb_options = "",
		kb_rules = "",
		follow_mouse = 1,
		sensitivity = 0,
		-- -1.0 - 1.0, 0 means no modification.
		accel_profile = "flat",
		touchpad = {
			natural_scroll = true,
		},
	},
})

-- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
hl.device({
	name = "epic-mouse-v1",
	sensitivity = -0.5,
})

hl.device({
	name = "hid-256c:006d-pen",
	output = "eDP-1",
})

--##################
--## KEYBINDINGS ###
--##################
-- See https://wiki.hyprland.org/Configuring/Keywords/

local mainMod = "SUPER"
-- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
hl.bind(mainMod .. " + " .. "Q", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + " .. "B", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + " .. "ESCAPE", hl.dsp.window.close())
hl.bind(mainMod .. " + " .. "M", hl.dsp.exit())
hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "V", hl.dsp.window.float())
hl.bind(mainMod .. " + " .. "R", hl.dsp.exec_cmd(runner))

-- dwindle
hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + " .. "J", hl.dsp.layout("togglesplit"))

-- Fullscreen binding
hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(
	mainMod .. " + " .. "SHIFT" .. " + " .. "F",
	hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" })
)
hl.bind(
	mainMod .. " + " .. "CTRL" .. " + " .. "F",
	hl.dsp.window.fullscreen_state({ internal = 0, client = 2, action = "toggle" })
)

-- Move focus with mainMod + arrow keys
-- hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))
-- hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))
-- hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))
-- hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]
hl.bind(mainMod .. " + " .. "I", hl.dsp.workspace.toggle_special("incognito"))
hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "I", hl.dsp.window.move({ workspace = "special:incognito" }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Scroll through existing workspaces with mainMod + scroll
-- hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))
-- hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Alt+Tab Scrolling through workspaces
hl.bind("ALT" .. " + " .. "TAB", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("ALT + SHIFT" .. " + " .. "TAB", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
-- hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true })
-- hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true })
-- hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
-- hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })
-- hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s 10%+"), { locked = true })
-- hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 10%-"), { locked = true })
--
-- -- Requires playerctl
-- hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
-- hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
-- hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

--#############################

--## WINDOWS AND WORKSPACES ###

--#############################

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

-- See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

-- Example windowrule

-- windowrule = float,class:^(kitty)$,title:^(kitty)$

-- Terminal Opacity + Translucent Background

hl.window_rule({
	name = "terminal_blur",
	match = {
		class = "^(org\\.wezfurlong\\.wezterm|kitty|com\\.mitchellh\\.ghostty)$",
	},
	opacity = "0.85 override 0.5 override",
})

-- Ignore maximize requests from apps. You'll probably like this.

hl.window_rule({
	name = "suppressevent_maximi",
	match = {
		class = ".*",
	},
	suppress_event = "maximize",
})

-- Fix some dragging issues with XWayland

hl.window_rule({
	name = "nofocus",
	match = {
		class = "^$",
		title = "^$",
		xwayland = 1,
		float = 1,
		fullscreen = 0,
		pin = 0,
	},
	no_focus = true,
})

-- Screensharing with XWayland

hl.window_rule({
	name = "opacity_0_0_override",
	match = {
		class = "^(xwaylandvideobridge)$",
	},
	opacity = "0.0 override",
})

hl.window_rule({
	name = "noanim",
	match = {
		class = "^(xwaylandvideobridge)$",
	},
	no_anim = true,
})

hl.window_rule({
	name = "noinitialfocus",
	match = {
		class = "^(xwaylandvideobridge)$",
	},
	no_initial_focus = true,
})

hl.window_rule({
	name = "maxsize_1_1",
	match = {
		class = "^(xwaylandvideobridge)$",
	},
	max_size = "1 1",
})

hl.window_rule({
	name = "noblur",
	match = {
		class = "^(xwaylandvideobridge)$",
	},
	no_blur = true,
})

hl.window_rule({
	name = "nofocus",
	match = {
		class = "^(xwaylandvideobridge)$",
	},
	no_focus = true,
})

-- Autostart
hl.on("hyprland.start", function()
	--	hl.exec_cmd("hyprpanel")
	--	hl.exec_cmd("swww-daemon")
	--	hl.exec_cmd("/home/shivraj/scripts/swww_randomizer.sh " .. wallpapers)
	--	hl.exec_cmd("walker --gapplication-service") -- app-launcher
	hl.exec_cmd("systemctl --user start hyprpolkitagent") -- auth agent
	hl.exec_cmd("sleep 1 && ~/.config/hypr/scripts/dynamic-borders.sh") -- script for removing borders from single windows
	hl.exec_cmd("kdeconnect-indicator") -- KDE Connect
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_DATA_DIRS PATH") -- screen sharing & XDG environment
end)

-- Ambxst
loadfile(os.getenv("HOME") .. "/.local/share/ambxst/hyprland.lua")()

-- OVERRIDES
-- Down here you can write or source anything that you want to override from Ambxst's settings.
hl.window_rule({ name = "browser_starting_width", match = { class = "firefox" }, scrolling_width = 1.0 })
