# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# User specific environment and startup programs
if [ -d "$HOME/.local/bin" ]; then export PATH="$PATH:$HOME/.local/bin" ; fi


# Added by Antigravity CLI installer
export PATH="/home/shivraj/.local/bin:$PATH"
